version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    cap_add:
      - SYS_NICE
    volumes:
      - ./userprofiles.sql:/docker-entrypoint-initdb.d/dump.sql